### ISSUE TITLE
SFD to OTF utility closed both ends of the points

### ISSUE THREAD

**Issue by alysdexia** [drdnar/GortonDigital#2]
https://everythingfonts.com/sfd-to-otf

![gorton fail](https://user-images.githubusercontent.com/28454125/44324556-df6eaa00-a40a-11e8-8576-b5540abadc5d.png)

**Comment by drdnar** [comment]
That's not a bug. The SFD files are just outlines. You need to apply some kind of transform to the strokes to give them width, e.g. using Font Forge's Expand Stroke function. Have you checked the releases page? There's OTF files already available for download.
